name: release (no-sign)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-and-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: windows
            rid: win-x64
            project: ./v2rayN/v2rayN.csproj
            os: windows-latest
            ext: zip
            extra-opts: '-p:EnableWindowsTargeting=true'
          - target: linux
            rid: linux-x64
            project: ./v2rayN.Desktop/v2rayN.Desktop.csproj
            os: ubuntu-24.04
            ext: tar.gz
            extra-opts: ''
          - target: osx
            rid: osx-x64
            project: ./v2rayN.Desktop/v2rayN.Desktop.csproj
            os: macos-latest
            ext: tar.gz
            extra-opts: ''
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.1xx'

    - name: Build v2rayN
      shell: bash
      working-directory: ./v2rayN
      run: dotnet publish ${{ matrix.project }} -c Release -r ${{ matrix.rid }} -p:SelfContained=true ${{ matrix.extra-opts }} -o release

    - name: Build AmazTool
      shell: bash
      working-directory: ./v2rayN
      run: dotnet publish ./AmazTool/AmazTool.csproj -c Release -r ${{ matrix.rid }} -p:SelfContained=true -p:PublishTrimmed=true ${{ matrix.extra-opts }} -o release

    - name: Remove debug symbols
      shell: bash
      run: find release -type f -name '*.pdb' -delete 2>/dev/null; true

    - name: Package
      shell: bash
      run: |
        cd v2rayN
        if [ "${{ matrix.target }}" = "windows" ]; then
          cd release && 7z a -tZip ../../v2rayN/v2rayN-${{ matrix.target }}-x64.zip . && cd ..
        else
          tar -czf v2rayN-${{ matrix.target }}-x64.tar.gz -C release .
        fi

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.release_tag }}
        files: |
          v2rayN/v2rayN-${{ matrix.target }}-x64.tar.gz
          v2rayN/v2rayN-${{ matrix.target }}-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
